#!/bin/bash

# description: links dotfiles to home dir

mkdir -p ~/.config

ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml
ln -sf ~/dotfiles/ssh/config ~/.ssh/config

echo "Dotfiles Linked!"
